clarify electrode position coordinates
NeurodataWithoutBorders/nwb-schema pull request #341
Opened 2019-12-14 01:50 UTC by bendichter

Make x,y,z consistent with CCF reference http://help.brain-map.org/display/mousebrain/API#API-DownloadAtlas3-DReferenceModels

2019-12-14 02:06 UTC, oruebel requested changes
Can you please add a corresponding item to the 2.2.0 release notes for the schema. The release notes are here https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/format_release_notes.rst Other than that this looks good.

2020-01-03 02:35 UTC, rly submitted a review, later dismissed

2020-01-04 00:42 UTC, rly submitted a review, later dismissed

2020-01-04 01:06 UTC, bendichter commented
@oruebel can you unblock this please?

2020-01-04 19:49 UTC, oruebel submitted a review, later dismissed

2020-01-04 19:50 UTC, oruebel approved these changes

2020-01-06 20:06 UTC, merged