add process attribute to TimeSeries.data
NeurodataWithoutBorders/nwb-schema pull request #425
Opened 2020-03-28 01:42 UTC by bendichter

fix #177

2020-03-30 06:50 UTC, rly commented
I also don't know what the best term is here. "Process" could work. What do you think about "continuity"? What we describe as step-forwards seems equivalent to a right-continuous step function.

2020-03-30 09:14 UTC, oruebel commented
The term ``process`` sounds strange to me. In particular it is fuzzy in terms of what kind of process this is referring to. If I understand this correctly, this refers to how the data was sampled to turn help the user determine how to interpolate and process the data. How about calling it ``sampling`` or ``sampling_strategy`` instead?

2020-03-30 12:19 UTC, bendichter commented
I mean the data is from a continuous vs discrete process. It's about the process of the underlying data, not how we sample it. Continuity also works and may be more intuitive.

2020-03-30 14:45 UTC, oruebel commented
In that case I like ``continuity`` better than ``process``. The problem with ``process`` is that even if the data comes from a continuous process, that does not mean that the approach we used to observe that process allows for continuous interpretation of the data. I think ``continuity`` is more explicit in that sense as it refers to the data itself not the process it represents.

2020-03-31 19:41 UTC, rly commented
I also wonder whether "discrete" is the best term for event data. "event" may be more intuitive. 

In signal processing terms, event data are analogous to a set of impulses (or delta functions). They have value x at exactly one time. All other values are 0. So "impulse" would also work, but that feels a little too technical and not as intuitive to the average neuroscientist. 

Also, a `continuity` field of `data` having the value `'discrete'` might suggest that the data come from a discrete set of values rather than a continuous range. If we want to use the value `'discrete'`, then naming the attribute `process` might be better and I would prefer it on the `TimeSeries` itself, rather than on `data`, since the time series (consisting of both time and values) is a discrete-time process.

In summary - I favor either:
1) name the attribute `"continuity"` and have the options be continuous, event, and step-forwards
2) name the attribute `'process'`, put it on the `TimeSeries` and have the options be continuous, discrete, and step-forwards

2020-03-31 22:43 UTC, oruebel commented
I would suggest the following 

* name: ``continuity`` 
* allowable values ``continuous``, ``instantaneous``, ``step``

**Reasoning**
* I think we should stick with common math terms to describe this 
* I think the analogous terms to ``continuous`` for  event data would be ``instantaneous`` 
    * I don't like the term ``discrete`` here because it can be misleading in that we have discretely sampled time in all cases anyways
    * The term ``event`` (while intuitive) seems like it may end up being to specific for a particlar case. Also, since this would be part of the base TimeSeries we should use a generic term. 
* I think we should use ``step`` instead of ``step-forwards``. In math a ``step`` function seems to always step forward and if we say ``step-forwards`` then it seems you would also have to include ``step-backwards``, which seems awkward. I would just stick with the convention that a step function steps fowards in time. 
* I prefer the name ``continuity`` because it describes what the data at hand actually is (which I think what we want to describe), whereas, ``process`` refers to what generated the data (which I don't think is what the intent of this is)

2020-03-31 23:27 UTC, rly commented
> I would suggest the following
> 
> * name: `continuity`
> * allowable values `continuous`, `instantaneous`, `step`

That sounds good to me.

2020-04-07 00:13 UTC, rly requested changes

2020-04-07 00:13 UTC, rly commented on core/nwb.base.yaml
> +        is interpretted, the way it is visualized, and what analysis methods are applicable.
```suggestion
      doc: Optionally describe the continuity of the data. Can be "continuous", "instantaneous", or
        "step". For example: A voltage trace would be "continuous", because samples 
        are recorded from a continuous process. An array of lick times would be "instantaneous", 
        because the data represents distinct moments in time. Times of image presentations would be  
        "step" because the picture remains the same until the next timepoint. This field is optional, 
        but is useful in providing information about the underlying data. It may inform the way this 
        data is interpreted, the way it is visualized, and what analysis methods are applicable.
```

2020-04-07 00:13 UTC, rly commented on core/nwb.base.yaml
> +        is interpretted, the way it is visualized, and what analysis methods are applicable.
I fixed some typos and reordered the examples to follow the list in the first sentence.

2020-04-07 05:29 UTC, oruebel commented
Where appropriate, we should define the default value (or even fix the value) for specific TimeSeries types. We could do this in separate PRs though.

2020-04-15 20:29 UTC, rly submitted a review, later dismissed

2020-04-17 17:00 UTC, bendichter commented
The CI has already started to pay off! There was a colon in the new "continuity" description that was messing up the yaml file.

2020-04-17 17:01 UTC, rly commented
Good catch!

2020-04-17 17:02 UTC, rly submitted a review, later dismissed

2020-04-17 17:19 UTC, rly submitted a review, later dismissed

2020-06-24 21:32 UTC, rly commented
Group decision was to add `enum` field to the schema language, add support for `enum` in HDMF, and add `enum` to the yaml in this PR.

2020-07-29 00:29 UTC, rly approved these changes

2020-07-29 01:46 UTC, merged