add cell_id to IntracellularElectrode
NeurodataWithoutBorders/nwb-schema pull request #512
Opened 2022-04-20 20:19 UTC by bendichter

## Summary of changes

fix #416

2022-04-20 20:38 UTC, oruebel requested changes
Can you please update the release notes: https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/format_release_notes.rst

Otherwise this looks good to me

2022-04-20 20:39 UTC, oruebel commented on core/nwb.icephys.yaml
> +    doc: unique ID of cell
```suggestion
    doc: unique ID of the cell
```

2022-04-20 20:39 UTC, oruebel commented
@rly it would be good if we could include this in the next release

2022-04-20 20:57 UTC, rly approved these changes

2022-04-21 17:20 UTC, oruebel approved these changes

2022-04-21 17:36 UTC, merged